enum errorCodes_e {
    UTILS_NO_ERROR,
	UTILS_NOT_FOUND,
    UTILS_CONVERT_NULL_DATE,
    UTILS_STRPTIME_FAIL,
    UTILS_TIMEGM_FAIL,
    UTILS_STRFTIME_FAIL,
    UTILS_INTEGER_NULL,
    UTILS_GETLOCALTIME_FAIL
};
void utilsErr(int utilsErrno);
